### ISSUE TITLE
Generic R Script

### ISSUE THREAD

**Issue by cfelletter** [BoulderCodeHub/Process-CRSS-Res#61]
@rabutler I'd like to push my new branch with my work on a Generic R Script for CRSS monthly/annual and for Daily to this repo. I don't currently have permission to push to this repo.

**Comment by rabutler-usbr** [comment]
@cfelletter you should now have access to push to the repository.

For this repo, we are using a fork based github model. So each one of us can have our own fork, make changes, and then issue PRs to get the code back into the master branch. 

Based on our conversation this morning, I'd recommend just pulling your code into the master branch, as long as it doesn't affect main.R, rather than maintaining a separate branch.
